Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2018-05, with the labels that each got.

#964 Skip tracing root Actuator endpoint
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthWebProperties.java
Labels: enhancement

#972 Issues #971 servlet context path
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebAutoConfiguration.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
Labels: enhancement, in progress

#974 Fix wrong sample code
  docs/src/main/asciidoc/spring-cloud-sleuth.adoc
Labels: documentation

#979 Fix minor typo (Slwuth -> Sleuth)
  README.adoc
  docs/src/main/asciidoc/features.adoc
Labels: documentation

#984 Updates to Brave 5
  pom.xml
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpClientParserTests.java
  spring-cloud-sleuth-dependencies/pom.xml
  spring-cloud-sleuth-samples/pom.xml
Labels: in progress

#995 fix #994 Make SpanSubscriber fake fuseability
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriber.java
Labels: bug
