Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2019-09, with the labels that each got.

#1428 Added support for quartz instrumentation
  docs/src/main/asciidoc/spring-cloud-sleuth.adoc
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/quartz/TraceQuartzAutoConfiguration.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/quartz/TracingJobListener.java
  spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/quartz/TraceQuartzAutoConfigurationTest.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/quartz/TracingJobListenerTest.java
Labels: enhancement

#1437 Fix TraceableExecutorService
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/TraceableExecutorService.java
Labels: waiting-for-triage

#1446 RestTemplate customizer can return an instance of rest template
  spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/DefaultZipkinRestTemplateCustomizer.java
  spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/ZipkinRestTemplateCustomizer.java
  spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinRestTemplateSenderConfiguration.java
Labels: enhancement

#1447 Fix ThreadPoolTaskScheduler proxy mechanism
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/async/ExecutorBeanPostProcessor.java
  tests/spring-cloud-sleuth-instrumentation-async-tests/src/test/java/org/springframework/cloud/sleuth/instrument/async/issues/issue410/Issue410Tests.java
Labels: bug

#1448 Added parametrization of RabbitMQ brokers
  spring-cloud-sleuth-zipkin/src/main/java/org/springframework/cloud/sleuth/zipkin2/sender/ZipkinRabbitSenderConfiguration.java
  spring-cloud-sleuth-zipkin/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: enhancement

#1451 Updating Zipkin settings in readme
  docs/src/main/asciidoc/sagan-boot.adoc
Labels: documentation
