Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2019-03, with the labels that each got.

#1225 Rename test class so it runs
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/ITTracingChannelInterceptorTests.java
Labels: waiting-for-triage

#1230 URL Cleanup
  .mvn/wrapper/maven-wrapper.properties
  benchmarks/pom.xml
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-dependencies/pom.xml
  spring-cloud-sleuth-samples/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml
  spring-cloud-sleuth-zipkin/pom.xml
  spring-cloud-starter-sleuth/pom.xml
  spring-cloud-starter-zipkin/pom.xml
Labels: waiting-for-triage

#1236 URL Cleanup
  benchmarks/pom.xml
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-dependencies/pom.xml
  spring-cloud-sleuth-reactor/pom.xml
  spring-cloud-sleuth-samples/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml
  spring-cloud-sleuth-stream/pom.xml
  spring-cloud-sleuth-zipkin-legacy/pom.xml
  spring-cloud-sleuth-zipkin-stream/pom.xml
  spring-cloud-sleuth-zipkin/pom.xml
  spring-cloud-starter-sleuth/pom.xml
  spring-cloud-starter-zipkin-legacy/pom.xml
  spring-cloud-starter-zipkin/pom.xml
Labels: waiting-for-triage

#1237 URL Cleanup
  .mvn/wrapper/maven-wrapper.properties
  benchmarks/pom.xml
  docs/pom.xml
  docs/src/main/asciidoc/ghpages.sh
  mvnw
  mvnw.cmd
  pom.xml
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-dependencies/pom.xml
  spring-cloud-sleuth-samples/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml
  spring-cloud-sleuth-zipkin/pom.xml
  spring-cloud-starter-sleuth/pom.xml
  spring-cloud-starter-zipkin/pom.xml
Labels: waiting-for-triage

#1264 URL Cleanup
  benchmarks/pom.xml
  docs/pom.xml
  pom.xml
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-core/src/test/resources/beans/applicationContext.xml
  spring-cloud-sleuth-dependencies/pom.xml
  spring-cloud-sleuth-samples/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml
  spring-cloud-sleuth-zipkin/pom.xml
  spring-cloud-starter-sleuth/pom.xml
  spring-cloud-starter-zipkin/pom.xml
  src/checkstyle/checkstyle-suppressions.xml
Labels: waiting-for-triage

#1271 URL Cleanup
  2.0.x/checkstyle-header.txt
  bootstrap/css/bootstrap-responsive.css
  bootstrap/css/bootstrap-responsive.min.css
  bootstrap/css/bootstrap.css
  bootstrap/css/bootstrap.min.css
  bootstrap/js/bootstrap.js
  bootstrap/js/bootstrap.min.js
  checkstyle-header.txt
Labels: waiting-for-triage

#1308 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  asciidoctor.css
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/features.adoc
  docs/src/main/asciidoc/intro.adoc
  docs/src/main/asciidoc/spring-cloud-sleuth.adoc
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/ProbabilityBasedSampler.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/issues/issue502/Issue502Tests.java
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/src/main/resources/static/sockjs-0.3.4.js
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/resources/application.yml
Labels: waiting-for-triage

#1309 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  asciidoctor.css
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/features.adoc
  docs/src/main/asciidoc/intro.adoc
  docs/src/main/asciidoc/sagan-index.adoc
  docs/src/main/asciidoc/spring-cloud-sleuth.adoc
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/ProbabilityBasedSampler.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/issues/issue502/Issue502Tests.java
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/src/main/resources/static/sockjs-0.3.4.js
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/resources/application.yml
Labels: waiting-for-triage

#1307 URL Cleanup
  .github/CONTRIBUTING.md
  README.adoc
  asciidoctor.css
  docs/src/main/asciidoc/intro.adoc
  docs/src/main/asciidoc/spring-cloud-sleuth.adoc
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/sampler/PercentageBasedSampler.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/HttpServletRequestExtractorTests.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/issues/issue502/Issue502Tests.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/zuul/TracePreZuulFilterTests.java
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/src/main/resources/static/sockjs-0.3.4.js
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/src/main/resources/static/stomp.js
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/src/main/resources/application.yml
  spring-cloud-sleuth-zipkin-stream/README.md
Labels: waiting-for-triage

#1297 URL Cleanup
  .settings.xml
  spring-cloud-sleuth-core/src/test/resources/beans/applicationContext.xml
Labels: waiting-for-triage

#1296 URL Cleanup
  .settings.xml
  spring-cloud-sleuth-core/src/test/resources/beans/applicationContext.xml
Labels: waiting-for-triage

#1281 Fix NullPointerException
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
Labels: bug

#1298 URL Cleanup
  benchmarks/pom.xml
  docs/pom.xml
  pom.xml
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-core/src/test/resources/beans/applicationContext.xml
  spring-cloud-sleuth-dependencies/pom.xml
  spring-cloud-sleuth-samples/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml
  spring-cloud-sleuth-zipkin/pom.xml
  spring-cloud-starter-sleuth/pom.xml
  spring-cloud-starter-zipkin/pom.xml
  src/checkstyle/checkstyle-suppressions.xml
Labels: waiting-for-triage

#1267 Enables Redis tracing by default.
  docs/src/main/asciidoc/spring-cloud-sleuth.adoc
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/redis/OnRedisEnabled.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/redis/TraceRedisAutoConfiguration.java
  spring-cloud-sleuth-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-sleuth-core/src/main/resources/META-INF/spring.factories
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/redis/TraceRedisAutoConfigurationTests.java
Labels: enhancement

#1222 Refactored SkipPatternProviderConfigTest to use WebApplicationContextRunner instead of manually instantiated configurations
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
Labels: waiting-for-triage
