Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2020-01, with the labels that each got.

#1513 Report HTTP pattern and handler function name for functional WebFlux routes.
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java
  tests/spring-cloud-sleuth-instrumentation-webflux-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFluxTests.java
Labels: enhancement

#1517 WebClient tracing should respect skipPattern.
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/TraceExchangeFilterFunctionHttpClientResponseTests.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/integration/WebClientTests.java
Labels: bug

#1519 Configure OpentracingAutoConfiguration after TraceAutoConfiguration.
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/opentracing/OpentracingAutoConfiguration.java
Labels: bug

#1522 Use actual log timestamp as logstash timestamp
  docs/src/main/asciidoc/intro.adoc
Labels: waiting-for-triage

#1525 Reduces overhead when using reactor by avoiding redundant context syncs
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/AbstractSleuthMethodInvocationProcessor.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/ReactorSleuthMethodInvocationProcessor.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriber.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriber.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriptionProvider.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceWebClientBeanPostProcessor.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectFluxTests.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/SleuthSpanCreatorAspectMonoTests.java
  tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/ScopePassingSpanSubscriberTests.java
Labels: enhancement

#1527 Addresses Spring Boot 2.3 drift
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/autoconfig/TraceAutoConfigurationWithDisabledSleuthTests.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/SkipPatternProviderConfigTest.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/exception/WebClientExceptionTests.java
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/src/test/java/sample/SampleFeignApplicationTests.java
  spring-cloud-sleuth-zipkin/pom.xml
  tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterWebIntegrationTests.java
  tests/spring-cloud-sleuth-instrumentation-reactor-tests/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/sample/FlatMapTests.java
Labels: waiting-for-triage

#1530 Cleanups of build including upgrade of Brave
  README.adoc
  benchmarks/pom.xml
  docs/pom.xml
  pom.xml
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignClientTests.java
  spring-cloud-sleuth-dependencies/pom.xml
  spring-cloud-sleuth-samples/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-feign/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-messaging/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-ribbon/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-test-core/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-websocket/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample-zipkin/pom.xml
  spring-cloud-sleuth-samples/spring-cloud-sleuth-sample/pom.xml
  spring-cloud-sleuth-zipkin/pom.xml
  spring-cloud-starter-sleuth/pom.xml
  spring-cloud-starter-zipkin/pom.xml
  tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-async-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-feign-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-grpc-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-hystrix-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-lettuce-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-messaging-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-messaging-tests/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/JmsTracingConfigurationTest.java
  tests/spring-cloud-sleuth-instrumentation-mvc-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-reactor-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-rpc-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-rxjava-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-scheduling-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-webflux-tests/pom.xml
  tests/spring-cloud-sleuth-instrumentation-zuul-tests/pom.xml
Labels: waiting-for-triage

#1531 Gh 1528 instrument feign sc loadbalancer client
  spring-cloud-sleuth-core/pom.xml
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignBlockingLoadBalancerClient.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignObjectWrapper.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignObjectWrapperTests.java
  tests/spring-cloud-sleuth-instrumentation-feign-tests/src/test/java/org/springframework/cloud/sleuth/instrument/feign/issues/issue1125delegates/ManuallyCreatedDelegateLoadBalancerFeignClientTests.java
Labels: bug

#1532 Moves client instrumentation off deprecated Brave code
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/HttpClientBeanPostProcessor.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/TraceRequestHttpHeadersFilter.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignBlockingLoadBalancerClient.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceLoadBalancerFeignClient.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignClient.java
Labels: enhancement

#1534 Moves server code of deprecated Brave and fixes remote addresses in Flux
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceWebFilter.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/zuul/TracePostZuulFilter.java
Labels: enhancement

#1541 Refactors some of the reactor code
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/LazySpanSubscriber.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorSleuth.java
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriptionProvider.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/reactor/SpanSubscriptionProviderTests.java
Labels: waiting-for-triage
