Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2020-06, with the labels that each got.

#1662 Fix incorrect properties used in baggage section
  docs/src/main/asciidoc/spring-cloud-sleuth.adoc
Labels: waiting-for-triage

#1665 Adds tracing on every factory methods in KafkaListenerContainerFactory
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration.java
  tests/spring-cloud-sleuth-instrumentation-messaging-tests/src/test/java/org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration1664Tests.java
Labels: bug

#1669 Optional/Null parameter used within @SpanTag
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/annotation/SpanTagAnnotationHandler.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/annotation/NullSpanTagAnnotationHandlerTests.java
  tests/spring-cloud-sleuth-instrumentation-mvc-tests/src/test/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterWebIntegrationTests.java
Labels: waiting for feedback
