Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2020-12, with the labels that each got.

#1805 TraceBaggageEntryConfigurationTests: eliminating nested tuples
  spring-cloud-sleuth-autoconfigure/src/test/java/org/springframework/cloud/sleuth/autoconfig/brave/TraceBaggageEntryConfigurationTests.java
Labels: task

#1810 Pad traceId with zeros in case of W3C propagation
  spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/bridge/W3CPropagation.java
  spring-cloud-sleuth-brave/src/test/java/org/springframework/cloud/sleuth/brave/bridge/W3CPropagationTest.java
Labels: bug

#1812 Fix typo in docs (index file)
  docs/src/main/asciidoc/_index.adoc
Labels: waiting-for-triage
