Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2021-01, with the labels that each got.

#1817 Set remote IP and port for servlet HTTP server traces.
  spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/bridge/BraveHttpServerRequest.java
  tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/web/TraceFilterTests.java
Labels: enhancement

#1821 [gh-1813] Fix properties prefix spring.sleuth.messaging
  docs/src/main/asciidoc/_configprops.adoc
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/instrument/messaging/BraveMessagingAutoConfiguration.java
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/messaging/SleuthMessagingProperties.java
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/messaging/TraceSpringIntegrationAutoConfiguration.java
  tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptorTest.java
Labels: bug

#1820 Fix documentation on number of supported tracers
  docs/src/main/asciidoc/getting-started.adoc
Labels: documentation

#1826 Remove spanExportable from sample log file entry in docs
  docs/src/main/asciidoc/project-features.adoc
Labels: documentation

#1828 Fixing the mockmvc-controller binding for the JMH tests
  benchmarks/src/main/java/org/springframework/cloud/sleuth/benchmarks/app/mvc/SleuthBenchmarkingSpringApp.java
  benchmarks/src/main/java/org/springframework/cloud/sleuth/benchmarks/app/mvc/controller/AsyncSimulationController.java
  benchmarks/src/test/java/org/springframework/cloud/sleuth/benchmarks/jmh/mvc/HttpFilterBenchmarksTests.java
Labels: enhancement

#1829 Fixing the mockmvc-controller binding for RestTemplate JMH tests
  benchmarks/src/test/java/org/springframework/cloud/sleuth/benchmarks/jmh/mvc/RestTemplateBenchmarkTests.java
Labels: enhancement

#1837 Fixing infinite wrapping of LazyTracingFeignClient
  spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TraceFeignObjectWrapper.java
  spring-cloud-sleuth-core/src/test/java/org/springframework/cloud/sleuth/instrument/web/client/feign/TracingFeignObjectWrapperTests.java
Labels: bug
