Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2021-11, with the labels that each got.

#2053 Refactored TraceListenerStrategy to better track current scope in case multiple connections are used
  spring-cloud-sleuth-api/src/main/java/org/springframework/cloud/sleuth/SpanAndScope.java
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/DataSourceProxyConfiguration.java
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/P6SpyConfiguration.java
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/jdbc/TraceJdbcAutoConfiguration.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceJdbcEventListener.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceListenerStrategy.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceQueryExecutionListener.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/task/TraceTaskExecutionListener.java
  tests/brave/spring-cloud-sleuth-instrumentation-jdbc-tests/src/test/java/org/springframework/cloud/sleuth/brave/instrument/jdbc/TraceJdbcEventListenerTests.java
  tests/brave/spring-cloud-sleuth-instrumentation-jdbc-tests/src/test/java/org/springframework/cloud/sleuth/brave/instrument/jdbc/TraceQueryExecutionListenerTests.java
  tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceJdbcEventListenerTests.java
  tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceListenerStrategyTests.java
  tests/common/src/main/java/org/springframework/cloud/sleuth/instrument/jdbc/TraceQueryExecutionListenerTests.java
Labels: enhancement

#2054 Make BraveKafkaStreamsAutoConfiguration public.
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/instrument/messaging/BraveKafkaStreamsAutoConfiguration.java
Labels: task

#2055 Fix HookRegisteringBeanFactoryPostProcessor to work with native.
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/reactor/TraceReactorAutoConfiguration.java
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/reactor/TraceReactorAutoConfigurationAccessorConfiguration.java
  tests/common/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/reactor/Issue866Configuration.java
Labels: task

#2060 Shutdown unused ClientResources
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/redis/TraceLettuceClientResourcesBeanPostProcessor.java
Labels: waiting-for-triage

#2046 Use Sleuth API for Redis instrumentation
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/brave/instrument/redis/BraveRedisAutoConfiguration.java
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/redis/TraceLettuceClientResourcesBeanPostProcessor.java
  spring-cloud-sleuth-brave/pom.xml
  spring-cloud-sleuth-instrumentation/pom.xml
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/redis/ClientResourcesBuilderCustomizer.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/redis/TraceLettuceClientResourcesBuilderCustomizer.java
Labels: waiting-for-triage
