Repository spring-cloud/spring-cloud-sleuth, pull requests merged in 2022-04, with the labels that each got.

#2143 Prometheus exemplars autoconfig
  docs/src/main/asciidoc/integrations.adoc
  spring-cloud-sleuth-autoconfigure/pom.xml
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/prometheus/PrometheusExemplarsAutoConfiguration.java
  spring-cloud-sleuth-autoconfigure/src/main/resources/META-INF/spring.factories
  spring-cloud-sleuth-autoconfigure/src/test/java/org/springframework/cloud/sleuth/autoconfig/instrument/prometheus/PrometheusExemplarsAutoConfigurationTests.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/prometheus/prometheus/LazySleuthSpanContextSupplier.java
  spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/prometheus/LazySleuthSpanContextSupplierTests.java
Labels: enhancement

#2145 fixing #2102 Netty reports LEAK while using reactor (Rsocket) with Sleuth
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/rsocket/PayloadUtils.java
Labels: bug

#2147 Relocate SleuthSpanContextSupplier
  spring-cloud-sleuth-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/instrument/prometheus/PrometheusExemplarsAutoConfiguration.java
  spring-cloud-sleuth-autoconfigure/src/test/java/org/springframework/cloud/sleuth/autoconfig/instrument/prometheus/PrometheusExemplarsAutoConfigurationTests.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/prometheus/LazySleuthSpanContextSupplier.java
  spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/prometheus/SleuthSpanContextSupplier.java
  spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/prometheus/LazySleuthSpanContextSupplierTests.java
  spring-cloud-sleuth-instrumentation/src/test/java/org/springframework/cloud/sleuth/instrument/prometheus/SleuthSpanContextSupplierTests.java
Labels: task
